name: env_pareto_front
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - black=23.11.0
  - blas=1.0=openblas
  - bleach=4.1.0
  - blosc=1.21.5
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.12.14
  - cached_property=1.5.2
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.12.14
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.2.0
  - cryptography=44.0.0
  - cycler=0.12.1
  - cymem=2.0.6
  - cython=3.0.11
  - cython-blis=0.7.9
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fftw=3.3.10
  - flake8=7.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gensim=4.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - ghostscript=10.03.1
  - giflib=5.2.2
  - gpy=1.13.2
  - graphite2=1.3.13
  - graphviz=8.1.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=9.0.0
  - hdf5=1.12.1
  - icu=73.2
  - idna=3.4
  - imagemagick=7.1.1_19
  - ipykernel=6.28.0
  - ipywidgets=8.1.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.13
  - keras=3.3.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcurl=8.7.1
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.5.1
  - libnghttp2=1.58.0
  - libopenblas=0.3.21
  - libpng=1.6.43
  - librsvg=2.58.0
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libtool=2.4.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=2.0.4
  - munkres=1.1.4
  - murmurhash=1.0.7
  - mypy_extensions=1.0.0
  - namex=0.0.8
  - nb_conda_kernels=2.3.1
  - nbclient=0.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nltk=3.8.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - openjpeg=2.5.2
  - openssl=3.4.0
  - optree=0.11.0
  - overrides=7.4.0
  - packaging=23.1
  - pandocfilters=1.5.0
  - pango=1.54.0
  - paramz=0.9.6
  - parso=0.8.3
  - pathspec=0.10.3
  - pathy=0.10.3
  - patsy=0.5.6
  - pcre2=10.43
  - pdfminer.six=20221105
  - pdfplumber=0.9.0
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.43.4
  - pkg-config=0.29.2
  - platformdirs=3.10.0
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pydantic=1.10.12
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytables=3.8.0
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - regex=2023.10.3
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shellingham=1.5.0
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.5.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - spacy-model-en_core_web_sm=3.5.0
  - sqlite=3.41.2
  - srsly=2.4.8
  - stack_data=0.2.0
  - statsmodels=0.14.1
  - tables=3.9.2
  - tenacity=8.2.2
  - terminado=0.17.1
  - thinc=8.1.10
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typer=0.4.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wand=0.6.10
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.13
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - arrow==1.3.0
      - astunparse==1.6.3
      - backcall==0.2.0
      - backports-tarfile==1.2.0
      - click-plugins==1.1.1
      - configargparse==1.7
      - connection-pool==0.0.3
      - datrie==0.8.2
      - docopt==0.6.2
      - docutils==0.21.2
      - dpath==2.2.0
      - dtool==3.27.0
      - dtool-annotation==0.1.1
      - dtool-cli==0.7.1
      - dtool-config==0.4.1
      - dtool-create==0.23.4
      - dtool-http==0.5.1
      - dtool-info==0.16.2
      - dtool-overlay==0.3.1
      - dtool-symlink==0.3.1
      - dtool-tag==0.1.1
      - dtoolcore==3.18.3
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - fst-pso==1.8.1
      - fuzzytm==2.0.9
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - humanfriendly==10.0
      - importlib-metadata==8.5.0
      - ipython==8.12.3
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jsonpointer==3.0.0
      - kaleido==0.2.1
      - keyring==25.5.0
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.6
      - matnexus==0.2.1
      - miniful==0.0.6
      - ml-dtypes==0.3.2
      - more-itertools==10.5.0
      - nbconvert==7.16.4
      - nh3==0.2.18
      - numba==0.60.0
      - numpy==1.24.4
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - parse==1.20.2
      - pipreqs==0.5.0
      - pkginfo==1.10.0
      - plac==1.4.3
      - plotly==5.20.0
      - protobuf==4.25.3
      - pulp==2.6.0
      - pybliometrics==4.1
      - pyfume==0.3.4
      - pymupdf==1.25.1
      - pynndescent==0.5.13
      - readme-renderer==44.0
      - requests-toolbelt==1.0.0
      - reretry==0.11.8
      - rfc3986==2.0.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scipy==1.10.1
      - simpful==2.12.0
      - smmap==5.0.1
      - snakemake==7.32.4
      - stopit==1.1.2
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - throttler==1.2.2
      - toposort==1.10
      - twine==5.1.1
      - types-python-dateutil==2.9.0.20241003
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - webcolors==24.11.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - yarg==0.1.9
      - yte==1.5.4
      - zipp==3.20.2